# Generated by Django 5.2.4 on 2025-11-25 20:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario/Atendedora')], default='usuario', max_length=20, verbose_name='Rol')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('orden', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='control.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['sucursal', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20, verbose_name='Tipo de Turno')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='control.sucursal', verbose_name='Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='control.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_maquina', models.IntegerField(verbose_name='Número de Máquina')),
                ('codigo_interno', models.CharField(blank=True, max_length=80, verbose_name='Código Interno')),
                ('nombre_juego', models.CharField(max_length=120, verbose_name='Nombre del Juego')),
                ('modelo', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=120, verbose_name='Número de Serie')),
                ('estado', models.CharField(choices=[('Operativa', 'Operativa'), ('Mantenimiento', 'Mantenimiento'), ('Retirada', 'Retirada')], default='Operativa', max_length=20, verbose_name='Estado')),
                ('ubicacion_detalle', models.CharField(blank=True, max_length=150, verbose_name='Detalle de Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='control.sucursal', verbose_name='Sucursal')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='control.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['sucursal', 'zona', 'numero_maquina'],
                'unique_together': {('zona', 'numero_maquina')},
            },
        ),
        migrations.CreateModel(
            name='LecturaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_maquina', models.IntegerField(verbose_name='Número de Máquina')),
                ('nombre_juego', models.CharField(max_length=120, verbose_name='Nombre del Juego')),
                ('entrada', models.IntegerField(verbose_name='Entrada')),
                ('salida', models.IntegerField(verbose_name='Salida')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='control.maquina', verbose_name='Máquina')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='control.sucursal', verbose_name='Sucursal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='control.turno', verbose_name='Turno')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='control.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Lectura de Máquina',
                'verbose_name_plural': 'Lecturas de Máquinas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
