# Generated by Django 5.2.4 on 2025-12-13 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_turno_zona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='zona',
        ),
        migrations.AddField(
            model_name='zona',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='zona',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zona',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='control.sucursal'),
        ),
    ]
