# Generated by Django 4.2.1 on 2026-03-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_asignacionturnoslot_asignacionturnozona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='rtp_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de retorno al jugador configurado en la máquina (ej: 92.5)', max_digits=5, null=True, verbose_name='RTP Objetivo (%)'),
        ),
    ]
