# Generated by Django 5.2.4 on 2025-12-13 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_zona_options_remove_turno_zona_zona_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['sucursal', 'orden', 'nombre'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.AddField(
            model_name='maquina',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='orden',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zona',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.sucursal'),
        ),
    ]
