# Generated by Django 5.2.4 on 2026-01-09 03:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_zona_options_maquina_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números y tener entre 8 y 12 dígitos.', regex='^\\d{8,12}$')]),
        ),
        migrations.CreateModel(
            name='CuadraturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja_base', models.IntegerField(default=0, verbose_name='Caja base / Fondo fijo')),
                ('retiro_diario', models.IntegerField(default=0, verbose_name='Retiro diario')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadraturas', to='control.sucursal', verbose_name='Sucursal')),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuadratura', to='control.turno', verbose_name='Turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadraturas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Cuadratura de Caja',
                'verbose_name_plural': 'Cuadraturas de Caja',
                'ordering': ['-created_at'],
            },
        ),
    ]
