# Generated by Django 5.2.4 on 2026-03-11 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_maquina_rtp_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('encargado', 'Encargado'), ('asistente', 'Asistente'), ('admin', 'Admin'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('tecnico', 'Técnico')], max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.CharField(blank=True, help_text='sin_asignacion | manual | timeout', max_length=50, null=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='control.sucursal')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='control.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Sesión',
                'verbose_name_plural': 'Registros de Sesión',
                'ordering': ['-hora_inicio'],
            },
        ),
    ]
