# Generated by Django 5.2.4 on 2026-03-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_registrosesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosesion',
            name='ip_cliente',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Cliente'),
        ),
    ]
