# Generated by Django 5.2.4 on 2026-01-09 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_sucursal_telefono_cuadraturacaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadraturaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.IntegerField(default=0, help_text='Valor calculado desde las lecturas del turno', verbose_name='Numeral del turno')),
                ('ajuste', models.IntegerField(default=0, help_text='Corrección manual si corresponde', verbose_name='Ajuste (+ / -)')),
                ('cuadratura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='control.cuadraturacaja', verbose_name='Cuadratura')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Numeral por Zona',
                'verbose_name_plural': 'Numerales por Zona',
                'ordering': ['zona__orden', 'zona__nombre'],
                'unique_together': {('cuadratura', 'zona')},
            },
        ),
    ]
