# Generated by Django 5.2.4 on 2026-03-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_registrosesion_ip_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosesion',
            name='ip_cliente',
        ),
    ]
