# Generated by Django 5.2.4 on 2026-01-09 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_cuadraturazona'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadraturaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSBANK', 'Transbank'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de pago')),
                ('monto', models.IntegerField(default=0, verbose_name='Monto')),
                ('referencia', models.CharField(blank=True, max_length=120, verbose_name='Referencia / Voucher')),
                ('cuadratura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='control.cuadraturacaja', verbose_name='Cuadratura')),
            ],
            options={
                'verbose_name': 'Pago de Cuadratura',
                'verbose_name_plural': 'Pagos de Cuadratura',
                'ordering': ['tipo'],
                'unique_together': {('cuadratura', 'tipo')},
            },
        ),
    ]
