# Generated by Django 5.2.4 on 2026-03-14 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_remove_registrosesion_ip_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=150)),
                ('nombre_sucursal', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión')], db_index=True, max_length=20)),
                ('modulo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('objeto_str', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='control.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registro de Actividades',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
