# Generated by Django 5.2.4 on 2026-01-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_cuadraturapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadraturaDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BILLETE', 'Billete'), ('MONEDA', 'Moneda')], max_length=10, verbose_name='Tipo')),
                ('denominacion', models.IntegerField(verbose_name='Denominación')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('cuadratura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='control.cuadraturacaja', verbose_name='Cuadratura')),
            ],
            options={
                'verbose_name': 'Denominación de Cuadratura',
                'verbose_name_plural': 'Denominaciones de Cuadratura',
                'ordering': ['tipo', 'denominacion'],
                'unique_together': {('cuadratura', 'tipo', 'denominacion')},
            },
        ),
        migrations.CreateModel(
            name='CuadraturaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SORTEOS', 'Sorteos'), ('GASTOS', 'Gastos'), ('SUELDO_EXT', 'Sueldo Ext.'), ('REDBANK', 'Redbank'), ('REGALOS', 'Regalos'), ('TAXI', 'Taxi'), ('JUGADOS', 'Jugados'), ('TRANSFER', 'Transfer'), ('OTRO', 'Otro'), ('DESCUADRE', 'Descuadre')], max_length=20, verbose_name='Tipo')),
                ('monto', models.IntegerField(default=0, verbose_name='Monto')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('cuadratura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='control.cuadraturacaja', verbose_name='Cuadratura')),
            ],
            options={
                'verbose_name': 'Movimiento de Cuadratura',
                'verbose_name_plural': 'Movimientos de Cuadratura',
                'ordering': ['tipo'],
                'unique_together': {('cuadratura', 'tipo')},
            },
        ),
    ]
