# Generated by Django 5.2.4 on 2026-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_registroactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='rtp_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de retorno al jugador configurado en la máquina (ej: 92.5)', max_digits=7, null=True, verbose_name='RTP Objetivo (%)'),
        ),
    ]
