# Generated by Django 5.2.4 on 2026-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_ampliar_rtp_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='rtp_creacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RTP registrado al momento de ingresar la máquina. Solo informativo, no se modifica.', max_digits=7, null=True, verbose_name='RTP de Ingreso (%)'),
        ),
    ]
