# Generated by Django 5.2.4 on 2026-01-22 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_remove_cuadraturacaja_sucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('caja_base', models.IntegerField(default=0)),
                ('retiro_diario', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('total_numeral', models.IntegerField(default=0)),
                ('total_gastos', models.IntegerField(default=0)),
                ('total_esperado', models.IntegerField(default=0)),
                ('total_efectivo_contado', models.IntegerField(default=0)),
                ('descuadre', models.IntegerField(default=0)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='control.sucursal')),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='control.turno')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='CierreTurnoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SORTEOS', 'Sorteos'), ('GASTOS', 'Gastos'), ('SUELDO_B', 'Sueldo B'), ('REDBANK', 'Redbank'), ('REGALOS', 'Regalos'), ('TAXI', 'Taxi'), ('JUGADOS', 'Jugados'), ('TRANSFER', 'Transfer'), ('OTROS_1', 'Otros 1'), ('OTROS_2', 'Otros 2'), ('OTROS_3', 'Otros 3'), ('DESCUADRE', 'Descuadre')], max_length=20)),
                ('monto', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='control.cierreturno')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='CierreTurnoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('REDBANK', 'Redbank'), ('TRANSFER', 'Transferencia'), ('OTRO', 'Otro')], max_length=20)),
                ('monto', models.IntegerField(default=0)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='control.cierreturno')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='CierreTurnoDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BILLETE', 'Billete'), ('MONEDA', 'Moneda')], max_length=10)),
                ('denominacion', models.IntegerField()),
                ('cantidad', models.IntegerField(default=0)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='control.cierreturno')),
            ],
            options={
                'ordering': ['-tipo', '-denominacion'],
                'unique_together': {('cierre', 'tipo', 'denominacion')},
            },
        ),
        migrations.CreateModel(
            name='CierreTurnoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.IntegerField(default=0)),
                ('ajuste', models.IntegerField(default=0)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='control.cierreturno')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.zona')),
            ],
            options={
                'ordering': ['zona__orden', 'zona__nombre'],
                'unique_together': {('cierre', 'zona')},
            },
        ),
    ]
