# Generated by Django 5.2.4 on 2026-01-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_cierreturno_cierreturnomovimiento_cierreturnopago_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maquina',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='zona',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='control.sucursal'),
        ),
        migrations.AddConstraint(
            model_name='lecturamaquina',
            constraint=models.UniqueConstraint(fields=('turno', 'maquina'), name='uniq_lectura_maquina_por_turno'),
        ),
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.UniqueConstraint(fields=('zona', 'numero_maquina'), name='uniq_maquina_por_zona'),
        ),
    ]
