# Generated by Django 5.2.4 on 2026-03-18 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_add_rtp_creacion_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('entrada_final', models.PositiveBigIntegerField(default=0, verbose_name='Contador entrada final')),
                ('salida_final', models.PositiveBigIntegerField(default=0, verbose_name='Contador salida final')),
                ('numeral', models.BigIntegerField(default=0, verbose_name='Numeral de retiro')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre_maquina', to='control.maquina', verbose_name='Máquina')),
                ('maquina_reemplazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='control.maquina', verbose_name='Máquina de reemplazo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.sucursal')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.zona')),
            ],
            options={
                'verbose_name': 'Cierre de Máquina',
                'verbose_name_plural': 'Cierres de Máquinas',
            },
        ),
    ]
