# Generated by Django 5.2.4 on 2026-01-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_maquina_unique_together_alter_zona_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierreturno',
            options={},
        ),
        migrations.RemoveField(
            model_name='cierreturno',
            name='actualizado_el',
        ),
        migrations.RemoveField(
            model_name='cierreturno',
            name='creado_el',
        ),
        migrations.AlterField(
            model_name='cierreturno',
            name='caja_base',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturno',
            name='descuadre',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturno',
            name='retiro_diario',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturno',
            name='total_efectivo_contado',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturno',
            name='total_esperado',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturno',
            name='total_gastos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturno',
            name='total_numeral',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturnozona',
            name='ajuste',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturnozona',
            name='numeral',
            field=models.BigIntegerField(default=0),
        ),
    ]
