# Generated by Django 5.2.4 on 2026-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_alter_cierreturno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreturno',
            name='prestamos_salida',
            field=models.IntegerField(default=0),
        ),
    ]
