# Generated by Django 5.2.4 on 2026-05-21 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_turno_ultima_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturamaquina',
            name='entrada',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='lecturamaquina',
            name='entrada_dia',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='lecturamaquina',
            name='salida',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='Salida'),
        ),
        migrations.AlterField(
            model_name='lecturamaquina',
            name='salida_dia',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
