# Generated by Django 5.2.4 on 2026-01-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_cierreturno_prestamos_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreturno',
            name='redbank_retiros',
            field=models.BigIntegerField(default=0),
        ),
    ]
