# Generated by Django 5.2.4 on 2026-05-30 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_alter_lecturamaquina_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informerecaudacion',
            name='notif_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_recaudacion', to='control.turno'),
        ),
    ]
