# Generated by Django 5.2.4 on 2026-02-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_cierreturno_redbank_retiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='contador_inicial_entrada',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maquina',
            name='contador_inicial_salida',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
