# Generated by Django 5.2.4 on 2026-02-03 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_maquina_contador_inicial_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_ciclo', models.DateField(default=django.utils.timezone.localdate)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_recaudacion', to='control.sucursal')),
            ],
        ),
    ]
