# Generated by Django 5.2.4 on 2026-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_ciclorecaudacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturamaquina',
            name='entrada_anterior',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturamaquina',
            name='entrada_dia',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturamaquina',
            name='salida_anterior',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturamaquina',
            name='salida_dia',
            field=models.BigIntegerField(default=0),
        ),
    ]
