# Generated by Django 5.2.4 on 2026-02-03 20:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_lecturamaquina_entrada_anterior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclorecaudacion',
            name='actualizado_en',
        ),
        migrations.AddField(
            model_name='ciclorecaudacion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciclorecaudacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ciclorecaudacion',
            name='inicio_ciclo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lecturamaquina',
            name='entrada',
            field=models.BigIntegerField(verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='lecturamaquina',
            name='salida',
            field=models.BigIntegerField(verbose_name='Salida'),
        ),
        migrations.AlterField(
            model_name='lecturamaquina',
            name='total',
            field=models.BigIntegerField(verbose_name='Total'),
        ),
    ]
