# Generated by Django 5.2.4 on 2026-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_remove_ciclorecaudacion_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreturno',
            name='total_lecturas_turno',
            field=models.BigIntegerField(default=0),
        ),
    ]
