# Generated by Django 5.2.4 on 2026-02-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_cierreturno_total_lecturas_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierreturnozona',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cierreturnozona',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='caja',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='descuadre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='detalle_entregado_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='prestamos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='redbank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='retiros',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierreturnozona',
            name='numeral',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='cierreturnozona',
            name='ajuste',
        ),
    ]
