# Generated by Django 5.2.4 on 2026-02-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_alter_cierreturnozona_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreturnozona',
            name='billete_10000_monto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='billete_1000_monto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='billete_20000_monto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='billete_2000_monto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='billete_5000_monto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cierreturnozona',
            name='monedas_monto',
            field=models.IntegerField(default=0),
        ),
    ]
