# Generated by Django 5.2.4 on 2026-02-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_cierreturnozona_billete_10000_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='servidor',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Servidor'),
        ),
    ]
