# Generated by Django 5.2.4 on 2026-02-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_maquina_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturamaquina',
            name='fecha_trabajo',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
