# Generated by Django 5.2.4 on 2026-02-06 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_lecturamaquina_fecha_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlLecturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_trabajo', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='control.sucursal')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles', to='control.turno')),
            ],
            options={
                'ordering': ['-fecha_trabajo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ControlLecturasLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_maquina', models.IntegerField()),
                ('servidor', models.CharField(blank=True, max_length=80)),
                ('juego', models.CharField(blank=True, max_length=120)),
                ('entrada_historica', models.BigIntegerField(default=0)),
                ('salida_historica', models.BigIntegerField(default=0)),
                ('entrada_parcial', models.BigIntegerField(default=0)),
                ('salida_parcial', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='control.controllecturas')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.maquina')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.zona')),
            ],
            options={
                'ordering': ['numero_maquina', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='controllecturas',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha_trabajo'), name='uniq_control_por_sucursal_fecha'),
        ),
    ]
