# Generated by Django 5.2.4 on 2026-02-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0024_controllecturas_controllecturaslinea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllecturas',
            name='total_general',
            field=models.BigIntegerField(default=0),
        ),
    ]
