# Generated by Django 5.2.4 on 2026-02-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_controllecturas_total_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadraturacajadiaria',
            name='numeral_total',
        ),
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='numeral_dia',
            field=models.BigIntegerField(default=0),
        ),
    ]
