# Generated by Django 5.2.4 on 2026-02-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0026_remove_cuadraturacajadiaria_numeral_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadraturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASTOS', 'Gastos'), ('SUELDOS', 'Sueldos'), ('REGALOS', 'Regalos'), ('TAXI', 'Taxi'), ('JUGADOS', 'Jugados'), ('OTROS', 'Otros')], max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('monto', models.IntegerField(default=0)),
                ('detalle', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuadratura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='control.cuadraturacajadiaria')),
            ],
            options={
                'ordering': ['tipo', 'creado_en'],
            },
        ),
    ]
