# Generated by Django 5.2.4 on 2026-02-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_cuadraturadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='caja_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
