# Generated by Django 5.2.4 on 2026-02-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_sucursal_caja_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='ef_1000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='ef_10000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='ef_2000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='ef_20000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='ef_5000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='ef_monedas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='prestamos',
            field=models.IntegerField(default=0),
        ),
    ]
