# Generated by Django 5.2.4 on 2026-02-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_cuadraturacajadiaria_ef_1000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadraturacajadiaria',
            name='ef_1000',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuadraturacajadiaria',
            name='ef_10000',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuadraturacajadiaria',
            name='ef_2000',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuadraturacajadiaria',
            name='ef_20000',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuadraturacajadiaria',
            name='ef_5000',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuadraturacajadiaria',
            name='ef_monedas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuadraturacajadiaria',
            name='prestamos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
