# Generated by Django 5.2.4 on 2026-02-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_alter_cuadraturacajadiaria_ef_1000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadraturacajadiaria',
            name='numeral_acumulado',
            field=models.BigIntegerField(default=0, verbose_name='Numeral Acumulado'),
        ),
    ]
