# Generated by Django 5.2.4 on 2026-02-08 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_alter_cuadraturacajadiaria_numeral_acumulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadraturadetalle',
            name='cuadratura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='control.cuadraturacajadiaria', verbose_name='Cuadratura'),
        ),
        migrations.AlterField(
            model_name='cuadraturadetalle',
            name='detalle',
            field=models.TextField(blank=True, default='', verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='cuadraturadetalle',
            name='monto',
            field=models.IntegerField(default=0, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='cuadraturadetalle',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cuadraturadetalle',
            name='tipo',
            field=models.CharField(choices=[('GASTOS', 'Gastos'), ('SUELDOS', 'Sueldos'), ('REGALOS', 'Regalos'), ('TAXI', 'Taxi'), ('JUGADOS', 'Jugados'), ('OTROS', 'Otros')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='cuadraturacajadiaria',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha'), name='unique_cuadratura_por_dia'),
        ),
    ]
