# Generated by Django 5.2.4 on 2026-02-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0032_alter_cuadraturadetalle_cuadratura_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuadraturacajadiaria',
            name='unique_cuadratura_por_dia',
        ),
        migrations.AddConstraint(
            model_name='cuadraturacajadiaria',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha'), name='uniq_cuadratura_por_sucursal_fecha'),
        ),
    ]
