# Generated by Django 5.2.4 on 2026-02-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_fix_creado_el_mysql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadraturacajadiaria',
            name='zona_1',
        ),
        migrations.RemoveField(
            model_name='cuadraturacajadiaria',
            name='zona_2',
        ),
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='prestamos_notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
