# Generated by Django 5.2.4 on 2026-02-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_remove_cuadraturacajadiaria_zona_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_asignados', to='control.sucursal', verbose_name='Sucursal Asignada'),
        ),
    ]
