# Generated by Django 5.2.4 on 2026-03-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_usuario_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='prestamos_acum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
