# Generated by Django 5.2.4 on 2026-03-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_cuadraturacajadiaria_prestamos_acum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuadraturacajadiaria',
            name='uniq_cuadratura_por_sucursal_fecha',
        ),
    ]
