# Generated by Django 5.2.4 on 2026-03-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0038_remove_cuadraturacajadiaria_uniq_cuadratura_por_sucursal_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadraturacajadiaria',
            name='ef_billetes_malos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
