# Generated by Django 5.2.4 on 2026-03-03 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_cuadraturacajadiaria_ef_billetes_malos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTurnoSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('redbank', 'Redbank'), ('servicio', 'Servicio')], max_length=20)),
                ('numero', models.PositiveSmallIntegerField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_slot', to='control.turno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_slot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('turno', 'tipo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurnoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banano', models.IntegerField(default=0)),
                ('prestamo', models.IntegerField(default=0)),
                ('retiros', models.IntegerField(default=0)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_zona', to='control.turno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_zona', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='control.zona')),
            ],
            options={
                'unique_together': {('turno', 'zona')},
            },
        ),
    ]
