# Generated by Django 5.2.4 on 2026-03-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0040_asignacionturnoslot_asignacionturnozona'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadraturaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banano', models.IntegerField(default=0)),
                ('prestamo', models.IntegerField(default=0)),
                ('retiros', models.IntegerField(default=0)),
                ('ef_20000', models.IntegerField(default=0)),
                ('ef_10000', models.IntegerField(default=0)),
                ('ef_5000', models.IntegerField(default=0)),
                ('ef_2000', models.IntegerField(default=0)),
                ('ef_1000', models.IntegerField(default=0)),
                ('monedas_monto', models.IntegerField(default=0)),
                ('detalle_entregado_total', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True, default='')),
                ('descuadre', models.IntegerField(default=0)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadraturas_zona', to='control.turno')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadraturas', to='control.zona')),
            ],
            options={
                'ordering': ['-creado_el'],
                'unique_together': {('turno', 'zona')},
            },
        ),
    ]
