# Generated by Django 5.2.4 on 2026-03-03 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0041_cuadraturazona'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio del ciclo')),
                ('fecha_cierre', models.DateField(verbose_name='Cierre del ciclo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('total_numeral', models.BigIntegerField(default=0)),
                ('total_entrada', models.BigIntegerField(default=0)),
                ('total_salida', models.BigIntegerField(default=0)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_recaudacion', to='control.sucursal')),
            ],
            options={
                'ordering': ['-fecha_cierre', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='InformeRecaudacionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.BigIntegerField(default=0)),
                ('prestamos', models.BigIntegerField(default=0)),
                ('retiros', models.BigIntegerField(default=0)),
                ('redbank', models.BigIntegerField(default=0)),
                ('transferencias', models.BigIntegerField(default=0)),
                ('sueldo_extra', models.BigIntegerField(default=0)),
                ('sorteos', models.BigIntegerField(default=0)),
                ('gastos', models.BigIntegerField(default=0)),
                ('regalos', models.BigIntegerField(default=0)),
                ('jugados', models.BigIntegerField(default=0)),
                ('otros', models.BigIntegerField(default=0)),
                ('billetes_malos', models.BigIntegerField(default=0)),
                ('descuadre', models.BigIntegerField(default=0)),
                ('total_caja', models.BigIntegerField(default=0)),
                ('informe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_caja', to='control.informerecaudacion')),
            ],
        ),
        migrations.CreateModel(
            name='InformeRecaudacionLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_nombre', models.CharField(blank=True, max_length=80)),
                ('numero_maquina', models.IntegerField()),
                ('codigo_interno', models.CharField(blank=True, max_length=80)),
                ('servidor', models.CharField(blank=True, max_length=60)),
                ('juego', models.CharField(blank=True, max_length=120)),
                ('hist_entrada_inicio', models.BigIntegerField(default=0)),
                ('hist_salida_inicio', models.BigIntegerField(default=0)),
                ('hist_entrada_cierre', models.BigIntegerField(default=0)),
                ('hist_salida_cierre', models.BigIntegerField(default=0)),
                ('parcial_entrada', models.BigIntegerField(default=0)),
                ('parcial_salida', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='control.informerecaudacion')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.zona')),
            ],
            options={
                'ordering': ['zona_nombre', 'numero_maquina'],
            },
        ),
        migrations.DeleteModel(
            name='CuadraturaZona',
        ),
    ]
