# Generated by Django 5.2.4 on 2026-03-03 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0042_informerecaudacion_informerecaudacioncaja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informerecaudacion',
            name='notificacion_consumida',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProgramacionRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='0=Lunes … 6=Domingo')),
                ('hora', models.TimeField(help_text='Hora del cierre automático (24h)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programacion_recaudacion', to='control.sucursal')),
            ],
        ),
    ]
