# Generated by Django 5.2.4 on 2026-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0043_informerecaudacion_notificacion_consumida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacionrecaudacion',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='programacionrecaudacion',
            name='dia_del_mes',
            field=models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que se ejecuta la recaudación (1-31)'),
        ),
    ]
